import type {
  Employee,
  Team,
  Pulse,
  Insight,
  Recognition,
  Announcement,
  Notification,
  KpiMetric,
  EngagementDataPoint,
  DepartmentEngagement,
  Message,
} from '@/lib/types'

// ---------------------------------------------------------------------------
// Employees
// ---------------------------------------------------------------------------

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    name: 'Carlos García Morales',
    email: 'carlos.garcia@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    department: 'Ingeniería',
    role: 'Desarrollador Senior',
    team: 'Equipo Backend',
    teamId: 'team-001',
    manager: 'Laura Sánchez Rivera',
    managerId: 'emp-006',
    startDate: '2021-03-15',
    status: 'active',
    engagementScore: 82,
    riskScore: 18,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 14,
    badges: [
      { id: 'b1', name: 'Innovador', icon: '💡', color: '#f59e0b', description: 'Por aportar ideas innovadoras', earnedAt: '2026-02-10' },
      { id: 'b2', name: 'Colaborador', icon: '🤝', color: '#10b981', description: 'Por apoyar a sus compañeros', earnedAt: '2026-04-01' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5601',
  },
  {
    id: 'emp-002',
    name: 'María López Hernández',
    email: 'maria.lopez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    department: 'Marketing',
    role: 'Gerente de Marketing Digital',
    team: 'Equipo Contenido',
    teamId: 'team-002',
    manager: 'Roberto Jiménez Castro',
    managerId: 'emp-007',
    startDate: '2020-07-01',
    status: 'active',
    engagementScore: 91,
    riskScore: 9,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 28,
    badges: [
      { id: 'b3', name: 'Estrella', icon: '⭐', color: '#f59e0b', description: 'Empleada del mes', earnedAt: '2026-04-30' },
      { id: 'b4', name: 'Líder', icon: '🏆', color: '#0c365c', description: 'Liderazgo excepcional', earnedAt: '2026-03-15' },
    ],
    location: 'Guadalajara',
    phone: '+52 33 1234-5602',
  },
  {
    id: 'emp-003',
    name: 'Juan Martínez Torres',
    email: 'juan.martinez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan',
    department: 'Ventas',
    role: 'Ejecutivo de Ventas',
    team: 'Equipo Ventas Norte',
    teamId: 'team-003',
    manager: 'Ana González Pérez',
    managerId: 'emp-008',
    startDate: '2022-01-10',
    status: 'active',
    engagementScore: 55,
    riskScore: 62,
    riskLevel: 'high',
    lastPulse: '2026-04-28',
    streakDays: 3,
    badges: [
      { id: 'b5', name: 'Vendedor Pro', icon: '📈', color: '#6366f1', description: 'Superar meta mensual', earnedAt: '2026-01-31' },
    ],
    location: 'Monterrey',
    phone: '+52 81 1234-5603',
  },
  {
    id: 'emp-004',
    name: 'Ana González Pérez',
    email: 'ana.gonzalez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    department: 'Ventas',
    role: 'Directora de Ventas',
    team: 'Equipo Ventas Norte',
    teamId: 'team-003',
    manager: 'Roberto Jiménez Castro',
    managerId: 'emp-007',
    startDate: '2019-05-20',
    status: 'active',
    engagementScore: 78,
    riskScore: 25,
    riskLevel: 'low',
    lastPulse: '2026-05-05',
    streakDays: 21,
    badges: [
      { id: 'b6', name: 'Mentora', icon: '🎓', color: '#8b5cf6', description: 'Por mentorear a nuevos empleados', earnedAt: '2026-03-01' },
    ],
    location: 'Monterrey',
    phone: '+52 81 1234-5604',
  },
  {
    id: 'emp-005',
    name: 'Luis Rodríguez Vega',
    email: 'luis.rodriguez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luis',
    department: 'Ingeniería',
    role: 'Ingeniero Full Stack',
    team: 'Equipo Frontend',
    teamId: 'team-001',
    manager: 'Laura Sánchez Rivera',
    managerId: 'emp-006',
    startDate: '2023-02-28',
    status: 'onboarding',
    engagementScore: 68,
    riskScore: 38,
    riskLevel: 'medium',
    lastPulse: '2026-05-04',
    streakDays: 7,
    badges: [],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5605',
  },
  {
    id: 'emp-006',
    name: 'Laura Sánchez Rivera',
    email: 'laura.sanchez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    department: 'Ingeniería',
    role: 'VP de Ingeniería',
    team: 'Liderazgo Técnico',
    teamId: 'team-001',
    manager: 'Roberto Jiménez Castro',
    managerId: 'emp-007',
    startDate: '2018-11-01',
    status: 'active',
    engagementScore: 88,
    riskScore: 12,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 45,
    badges: [
      { id: 'b7', name: 'Visionaria', icon: '🔭', color: '#0c365c', description: 'Visión estratégica', earnedAt: '2025-12-15' },
      { id: 'b8', name: 'Mentora', icon: '🎓', color: '#8b5cf6', description: 'Mentoría sobresaliente', earnedAt: '2026-01-10' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5606',
  },
  {
    id: 'emp-007',
    name: 'Roberto Jiménez Castro',
    email: 'roberto.jimenez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    department: 'Dirección General',
    role: 'CEO',
    team: 'Dirección',
    teamId: 'team-006',
    manager: '',
    managerId: '',
    startDate: '2017-01-01',
    status: 'active',
    engagementScore: 95,
    riskScore: 5,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 60,
    badges: [
      { id: 'b9', name: 'Fundador', icon: '🚀', color: '#0c365c', description: 'Fundador de la empresa', earnedAt: '2017-01-01' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5607',
  },
  {
    id: 'emp-008',
    name: 'Patricia Flores Ríos',
    email: 'patricia.flores@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    department: 'Recursos Humanos',
    role: 'Directora de RRHH',
    team: 'Equipo RRHH',
    teamId: 'team-004',
    manager: 'Roberto Jiménez Castro',
    managerId: 'emp-007',
    startDate: '2019-08-15',
    status: 'active',
    engagementScore: 85,
    riskScore: 15,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 33,
    badges: [
      { id: 'b10', name: 'Cultura', icon: '🌟', color: '#ec4899', description: 'Construcción de cultura organizacional', earnedAt: '2026-02-14' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5608',
  },
  {
    id: 'emp-009',
    name: 'Diego Hernández Mora',
    email: 'diego.hernandez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    department: 'Producto',
    role: 'Product Manager Senior',
    team: 'Equipo Producto',
    teamId: 'team-005',
    manager: 'Laura Sánchez Rivera',
    managerId: 'emp-006',
    startDate: '2021-09-01',
    status: 'active',
    engagementScore: 76,
    riskScore: 30,
    riskLevel: 'medium',
    lastPulse: '2026-05-05',
    streakDays: 10,
    badges: [
      { id: 'b11', name: 'Orientado al Usuario', icon: '🎯', color: '#14b8a6', description: 'Foco en experiencia del cliente', earnedAt: '2026-04-15' },
    ],
    location: 'Guadalajara',
    phone: '+52 33 1234-5609',
  },
  {
    id: 'emp-010',
    name: 'Sofía Ramírez Duarte',
    email: 'sofia.ramirez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    department: 'Marketing',
    role: 'Diseñadora UX/UI',
    team: 'Equipo Diseño',
    teamId: 'team-002',
    manager: 'María López Hernández',
    managerId: 'emp-002',
    startDate: '2022-06-15',
    status: 'active',
    engagementScore: 89,
    riskScore: 11,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 22,
    badges: [
      { id: 'b12', name: 'Creativa', icon: '🎨', color: '#f97316', description: 'Creatividad excepcional', earnedAt: '2026-03-20' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5610',
  },
  {
    id: 'emp-011',
    name: 'Miguel Ángel Torres Blanco',
    email: 'miguel.torres@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Miguel',
    department: 'Ingeniería',
    role: 'DevOps Engineer',
    team: 'Equipo Infraestructura',
    teamId: 'team-001',
    manager: 'Laura Sánchez Rivera',
    managerId: 'emp-006',
    startDate: '2020-11-30',
    status: 'active',
    engagementScore: 71,
    riskScore: 42,
    riskLevel: 'medium',
    lastPulse: '2026-04-30',
    streakDays: 5,
    badges: [
      { id: 'b13', name: 'Disponibilidad', icon: '⚡', color: '#eab308', description: 'Mantiene 99.9% uptime', earnedAt: '2026-02-28' },
    ],
    location: 'Querétaro',
    phone: '+52 44 1234-5611',
  },
  {
    id: 'emp-012',
    name: 'Valentina Moreno Castillo',
    email: 'valentina.moreno@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    department: 'Éxito del Cliente',
    role: 'Customer Success Manager',
    team: 'Equipo CS',
    teamId: 'team-006',
    manager: 'Roberto Jiménez Castro',
    managerId: 'emp-007',
    startDate: '2021-04-19',
    status: 'active',
    engagementScore: 83,
    riskScore: 20,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 18,
    badges: [
      { id: 'b14', name: 'NPS 10', icon: '💎', color: '#0c365c', description: 'NPS perfecto de clientes', earnedAt: '2026-04-20' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5612',
  },
  {
    id: 'emp-013',
    name: 'Fernando Reyes Gutiérrez',
    email: 'fernando.reyes@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fernando',
    department: 'Ventas',
    role: 'Account Executive',
    team: 'Equipo Ventas Sur',
    teamId: 'team-003',
    manager: 'Ana González Pérez',
    managerId: 'emp-004',
    startDate: '2023-08-07',
    status: 'active',
    engagementScore: 62,
    riskScore: 55,
    riskLevel: 'high',
    lastPulse: '2026-04-25',
    streakDays: 2,
    badges: [],
    location: 'Puebla',
    phone: '+52 22 1234-5613',
  },
  {
    id: 'emp-014',
    name: 'Isabella Cruz Medina',
    email: 'isabella.cruz@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    department: 'Recursos Humanos',
    role: 'Especialista en Talento',
    team: 'Equipo RRHH',
    teamId: 'team-004',
    manager: 'Patricia Flores Ríos',
    managerId: 'emp-008',
    startDate: '2022-03-14',
    status: 'active',
    engagementScore: 80,
    riskScore: 22,
    riskLevel: 'low',
    lastPulse: '2026-05-05',
    streakDays: 16,
    badges: [
      { id: 'b15', name: 'Reclutadora Top', icon: '🏅', color: '#f59e0b', description: 'Mejor desempeño en reclutamiento', earnedAt: '2026-04-05' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5614',
  },
  {
    id: 'emp-015',
    name: 'Alejandro Vargas Núñez',
    email: 'alejandro.vargas@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro',
    department: 'Ingeniería',
    role: 'Data Scientist',
    team: 'Equipo Datos',
    teamId: 'team-001',
    manager: 'Laura Sánchez Rivera',
    managerId: 'emp-006',
    startDate: '2022-10-03',
    status: 'active',
    engagementScore: 74,
    riskScore: 35,
    riskLevel: 'medium',
    lastPulse: '2026-05-03',
    streakDays: 9,
    badges: [
      { id: 'b16', name: 'Analítico', icon: '📊', color: '#6366f1', description: 'Insights basados en datos', earnedAt: '2026-03-10' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5615',
  },
  {
    id: 'emp-016',
    name: 'Camila Jiménez Serrano',
    email: 'camila.jimenez@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Camila',
    department: 'Producto',
    role: 'UX Researcher',
    team: 'Equipo Producto',
    teamId: 'team-005',
    manager: 'Diego Hernández Mora',
    managerId: 'emp-009',
    startDate: '2023-05-22',
    status: 'active',
    engagementScore: 77,
    riskScore: 28,
    riskLevel: 'low',
    lastPulse: '2026-05-05',
    streakDays: 12,
    badges: [],
    location: 'Guadalajara',
    phone: '+52 33 1234-5616',
  },
  {
    id: 'emp-017',
    name: 'Emilio Castro Domínguez',
    email: 'emilio.castro@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emilio',
    department: 'Ventas',
    role: 'SDR',
    team: 'Equipo Ventas Norte',
    teamId: 'team-003',
    manager: 'Ana González Pérez',
    managerId: 'emp-004',
    startDate: '2024-01-15',
    status: 'onboarding',
    engagementScore: 58,
    riskScore: 68,
    riskLevel: 'critical',
    lastPulse: '2026-04-20',
    streakDays: 1,
    badges: [],
    location: 'Monterrey',
    phone: '+52 81 1234-5617',
  },
  {
    id: 'emp-018',
    name: 'Natalia Herrera Peña',
    email: 'natalia.herrera@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natalia',
    department: 'Marketing',
    role: 'Growth Hacker',
    team: 'Equipo Crecimiento',
    teamId: 'team-002',
    manager: 'María López Hernández',
    managerId: 'emp-002',
    startDate: '2022-09-01',
    status: 'active',
    engagementScore: 85,
    riskScore: 17,
    riskLevel: 'low',
    lastPulse: '2026-05-06',
    streakDays: 25,
    badges: [
      { id: 'b17', name: 'Crecimiento', icon: '📈', color: '#10b981', description: 'Mayor crecimiento de usuarios', earnedAt: '2026-04-28' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5618',
  },
  {
    id: 'emp-019',
    name: 'Rodrigo Blanco Aguirre',
    email: 'rodrigo.blanco@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rodrigo',
    department: 'Éxito del Cliente',
    role: 'Customer Support Lead',
    team: 'Equipo Soporte',
    teamId: 'team-006',
    manager: 'Valentina Moreno Castillo',
    managerId: 'emp-012',
    startDate: '2021-07-12',
    status: 'active',
    engagementScore: 72,
    riskScore: 40,
    riskLevel: 'medium',
    lastPulse: '2026-05-04',
    streakDays: 8,
    badges: [
      { id: 'b18', name: 'Resolución', icon: '🛡️', color: '#0c365c', description: 'Mayor tasa de resolución en 1er contacto', earnedAt: '2026-03-31' },
    ],
    location: 'Ciudad de México',
    phone: '+52 55 1234-5619',
  },
  {
    id: 'emp-020',
    name: 'Daniela Ortega Lozano',
    email: 'daniela.ortega@climaai.mx',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniela',
    department: 'Producto',
    role: 'Product Designer',
    team: 'Equipo Producto',
    teamId: 'team-005',
    manager: 'Diego Hernández Mora',
    managerId: 'emp-009',
    startDate: '2023-11-06',
    status: 'active',
    engagementScore: 79,
    riskScore: 26,
    riskLevel: 'low',
    lastPulse: '2026-05-05',
    streakDays: 11,
    badges: [
      { id: 'b19', name: 'Diseño', icon: '✏️', color: '#f97316', description: 'Diseño destacado del trimestre', earnedAt: '2026-04-10' },
    ],
    location: 'Guadalajara',
    phone: '+52 33 1234-5620',
  },
]

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-001',
    name: 'Ingeniería',
    department: 'Ingeniería',
    managerId: 'emp-006',
    managerName: 'Laura Sánchez Rivera',
    memberCount: 5,
    engagementScore: 76,
    riskScore: 28,
    color: '#0c365c',
  },
  {
    id: 'team-002',
    name: 'Marketing',
    department: 'Marketing',
    managerId: 'emp-002',
    managerName: 'María López Hernández',
    memberCount: 3,
    engagementScore: 88,
    riskScore: 14,
    color: '#167fd0',
  },
  {
    id: 'team-003',
    name: 'Ventas',
    department: 'Ventas',
    managerId: 'emp-004',
    managerName: 'Ana González Pérez',
    memberCount: 4,
    engagementScore: 62,
    riskScore: 55,
    color: '#6366f1',
  },
  {
    id: 'team-004',
    name: 'Recursos Humanos',
    department: 'Recursos Humanos',
    managerId: 'emp-008',
    managerName: 'Patricia Flores Ríos',
    memberCount: 2,
    engagementScore: 83,
    riskScore: 18,
    color: '#ec4899',
  },
  {
    id: 'team-005',
    name: 'Producto',
    department: 'Producto',
    managerId: 'emp-009',
    managerName: 'Diego Hernández Mora',
    memberCount: 3,
    engagementScore: 77,
    riskScore: 27,
    color: '#14b8a6',
  },
  {
    id: 'team-006',
    name: 'Éxito del Cliente',
    department: 'Éxito del Cliente',
    managerId: 'emp-012',
    managerName: 'Valentina Moreno Castillo',
    memberCount: 3,
    engagementScore: 79,
    riskScore: 25,
    color: '#f97316',
  },
]

// ---------------------------------------------------------------------------
// Pulses
// ---------------------------------------------------------------------------

export const MOCK_PULSES: Pulse[] = [
  {
    id: 'pulse-001',
    title: 'Pulso Semanal de Bienestar',
    description: 'Verificación rápida del estado emocional y bienestar de tu equipo esta semana.',
    status: 'active',
    type: 'mood',
    participationRate: 84,
    createdAt: '2026-05-01T09:00:00Z',
    questions: [
      { id: 'q1', text: '¿Cómo te sientes hoy?', type: 'emoji' },
      { id: 'q2', text: '¿Qué tan manejable es tu carga de trabajo?', type: 'scale' },
      { id: 'q3', text: '¿Hay algo que te preocupe esta semana?', type: 'text' },
    ],
    responses: 17,
    totalEmployees: 20,
  },
  {
    id: 'pulse-002',
    title: 'Encuesta de Compromiso Q2 2026',
    description: 'Evaluación trimestral del nivel de compromiso y satisfacción laboral.',
    status: 'completed',
    type: 'engagement',
    participationRate: 95,
    createdAt: '2026-04-01T08:00:00Z',
    completedAt: '2026-04-15T23:59:00Z',
    questions: [
      { id: 'q4', text: '¿En una escala del 1 al 10, qué tan comprometido te sientes con la empresa?', type: 'scale' },
      { id: 'q5', text: '¿Recomendarías esta empresa como un excelente lugar para trabajar?', type: 'scale' },
      { id: 'q6', text: '¿Te sientes reconocido por tu trabajo?', type: 'multiple', options: ['Siempre', 'A veces', 'Rara vez', 'Nunca'] },
      { id: 'q7', text: '¿Qué mejorarías en tu entorno de trabajo?', type: 'text' },
    ],
    responses: 19,
    totalEmployees: 20,
  },
  {
    id: 'pulse-003',
    title: 'Medición eNPS Mayo 2026',
    description: 'Medición del Net Promoter Score de empleados para identificar promotores y detractores.',
    status: 'active',
    type: 'enps',
    participationRate: 70,
    createdAt: '2026-05-05T10:00:00Z',
    questions: [
      { id: 'q8', text: '¿Qué tan probable es que recomiendes esta empresa como lugar de trabajo a un amigo? (0-10)', type: 'scale' },
      { id: 'q9', text: '¿Cuál es la razón principal de tu calificación?', type: 'text' },
    ],
    responses: 14,
    totalEmployees: 20,
  },
  {
    id: 'pulse-004',
    title: 'Feedback Post Onboarding',
    description: 'Evaluación de la experiencia de integración para nuevos colaboradores.',
    status: 'completed',
    type: 'custom',
    participationRate: 100,
    createdAt: '2026-03-01T09:00:00Z',
    completedAt: '2026-03-15T23:59:00Z',
    questions: [
      { id: 'q10', text: '¿Qué tan satisfecho estás con el proceso de onboarding?', type: 'scale' },
      { id: 'q11', text: '¿Te sentiste bienvenido por tu equipo?', type: 'multiple', options: ['Totalmente', 'En su mayoría', 'Algo', 'No realmente'] },
      { id: 'q12', text: '¿Qué mejorarías del proceso de integración?', type: 'text' },
    ],
    responses: 2,
    totalEmployees: 2,
  },
  {
    id: 'pulse-005',
    title: 'Clima Laboral Junio 2026',
    description: 'Encuesta mensual de clima organizacional y condiciones de trabajo.',
    status: 'scheduled',
    type: 'engagement',
    participationRate: 0,
    createdAt: '2026-05-07T14:00:00Z',
    scheduledAt: '2026-06-01T09:00:00Z',
    questions: [
      { id: 'q13', text: '¿Cómo calificarías el ambiente de trabajo en tu equipo?', type: 'scale' },
      { id: 'q14', text: '¿Tienes las herramientas necesarias para hacer bien tu trabajo?', type: 'multiple', options: ['Sí, completamente', 'En su mayoría sí', 'Parcialmente', 'No'] },
      { id: 'q15', text: '¿Sientes que tu opinión es valorada?', type: 'scale' },
      { id: 'q16', text: '¿Qué podría hacer la empresa para mejorar tu experiencia?', type: 'text' },
    ],
    responses: 0,
    totalEmployees: 20,
  },
  {
    id: 'pulse-006',
    title: 'Pulso Rápido de Lunes',
    description: 'Check-in de inicio de semana para mantener el dedo en el pulso del equipo.',
    status: 'completed',
    type: 'mood',
    participationRate: 90,
    createdAt: '2026-04-28T08:00:00Z',
    completedAt: '2026-04-28T23:59:00Z',
    questions: [
      { id: 'q17', text: '¿Con qué emoji describes tu energía de inicio de semana?', type: 'emoji' },
      { id: 'q18', text: '¿Tienes claridad sobre tus prioridades de la semana?', type: 'multiple', options: ['Sí, totalmente', 'Más o menos', 'No mucho', 'Para nada'] },
    ],
    responses: 18,
    totalEmployees: 20,
  },
  {
    id: 'pulse-007',
    title: 'Encuesta de Beneficios 2026',
    description: 'Consulta sobre los beneficios actuales y qué nuevos beneficios les gustaría recibir.',
    status: 'draft',
    type: 'custom',
    participationRate: 0,
    createdAt: '2026-05-07T16:00:00Z',
    questions: [
      { id: 'q19', text: '¿Qué beneficio valoras más actualmente?', type: 'multiple', options: ['Seguro médico', 'Home office', 'Días de vacaciones adicionales', 'Capacitación', 'Bonos de desempeño'] },
      { id: 'q20', text: '¿Qué beneficio te gustaría que la empresa agregara?', type: 'text' },
      { id: 'q21', text: '¿Qué tan satisfecho estás con tu compensación total?', type: 'scale' },
    ],
    responses: 0,
    totalEmployees: 20,
  },
  {
    id: 'pulse-008',
    title: 'Evaluación de Liderazgo Q1',
    description: 'Evaluación anónima del estilo de liderazgo de los managers por parte de sus equipos.',
    status: 'completed',
    type: 'custom',
    participationRate: 88,
    createdAt: '2026-03-25T09:00:00Z',
    completedAt: '2026-04-05T23:59:00Z',
    questions: [
      { id: 'q22', text: '¿Tu manager te proporciona retroalimentación útil y oportuna?', type: 'scale' },
      { id: 'q23', text: '¿Tu manager apoya tu desarrollo profesional?', type: 'scale' },
      { id: 'q24', text: '¿Qué podría mejorar tu manager en su estilo de liderazgo?', type: 'text' },
    ],
    responses: 16,
    totalEmployees: 18,
  },
]

// ---------------------------------------------------------------------------
// Insights
// ---------------------------------------------------------------------------

export const MOCK_INSIGHTS: Insight[] = [
  {
    id: 'insight-001',
    type: 'burnout',
    severity: 'critical',
    title: 'Riesgo alto de agotamiento en Equipo de Ventas',
    description: 'Los indicadores de bienestar del Equipo de Ventas muestran una caída del 23% en las últimas 4 semanas. La participación en pulsos disminuyó a 45% y los scores de humor promedio están por debajo de 3/5.',
    affectedEmployees: 4,
    affectedTeams: ['team-003'],
    recommendation: 'Programar sesiones 1:1 urgentes con la manager del equipo. Considerar redistribuir la carga de trabajo y revisar las métricas de cuota del trimestre.',
    confidence: 91,
    createdAt: '2026-05-06T10:00:00Z',
    isRead: false,
  },
  {
    id: 'insight-002',
    type: 'retention',
    severity: 'warning',
    title: 'Empleado con alto potencial en riesgo de fuga',
    description: 'Emilio Castro Domínguez presenta patrones de desconexión: reducción de participación en actividades de equipo, respuestas negativas en pulsos y ausencias frecuentes en reuniones voluntarias.',
    affectedEmployees: 1,
    affectedTeams: ['team-003'],
    recommendation: 'El manager directo debe tener una conversación de carrera en los próximos 7 días. Explorar oportunidades de crecimiento o cambio de rol.',
    confidence: 85,
    createdAt: '2026-05-05T14:30:00Z',
    isRead: false,
  },
  {
    id: 'insight-003',
    type: 'engagement',
    severity: 'info',
    title: 'Marketing lidera el engagement por tercer mes consecutivo',
    description: 'El equipo de Marketing mantiene el puntaje de engagement más alto de la empresa (88/100). Sus prácticas de reconocimiento frecuente y comunicación abierta son factores clave.',
    affectedEmployees: 3,
    affectedTeams: ['team-002'],
    recommendation: 'Documentar y compartir las mejores prácticas del equipo de Marketing con otros managers. Considerar a María López como mentora de liderazgo.',
    confidence: 96,
    createdAt: '2026-05-04T09:00:00Z',
    isRead: true,
  },
  {
    id: 'insight-004',
    type: 'morale',
    severity: 'warning',
    title: 'Descenso en la moral del equipo de Ingeniería',
    description: 'Tras el lanzamiento intensivo de Q1, el equipo de Ingeniería muestra signos de fatiga. El puntaje de engagement cayó 8 puntos vs. el mes anterior. 3 de 5 miembros reportaron carga alta.',
    affectedEmployees: 3,
    affectedTeams: ['team-001'],
    recommendation: 'Planificar una jornada de descanso o actividad de team building. Evaluar la distribución de tareas críticas para Q3 y asegurar que el equipo tome sus días de descanso.',
    confidence: 78,
    createdAt: '2026-05-03T11:15:00Z',
    isRead: false,
  },
  {
    id: 'insight-005',
    type: 'recognition',
    severity: 'info',
    title: 'Brecha de reconocimiento en departamento de Éxito del Cliente',
    description: 'El equipo de Éxito del Cliente ha recibido un 40% menos reconocimientos que el promedio de la empresa en los últimos 30 días, a pesar de mantener métricas de satisfacción al cliente sobresalientes.',
    affectedEmployees: 3,
    affectedTeams: ['team-006'],
    recommendation: 'Programar un evento de reconocimiento formal para el equipo de CS. Activar recordatorios para que otros equipos reconozcan la labor de soporte al cliente.',
    confidence: 88,
    createdAt: '2026-05-02T16:45:00Z',
    isRead: true,
  },
  {
    id: 'insight-006',
    type: 'burnout',
    severity: 'warning',
    title: 'Patrón de trabajo fuera de horario detectado',
    description: 'Los registros de actividad muestran que 6 empleados envían mensajes y commits con frecuencia entre las 9 PM y la medianoche. Esto se correlaciona con scores de bienestar más bajos.',
    affectedEmployees: 6,
    affectedTeams: ['team-001', 'team-005'],
    recommendation: 'Compartir políticas de desconexión digital. Revisar en la próxima reunión de managers si las cargas de trabajo son sostenibles y fomentar el respeto a los límites de horario.',
    confidence: 73,
    createdAt: '2026-05-01T08:30:00Z',
    isRead: false,
  },
  {
    id: 'insight-007',
    type: 'retention',
    severity: 'info',
    title: 'Oportunidad: empleados con alto potencial listos para promoción',
    description: 'El análisis de desempeño y engagement identifica a 3 empleados con perfil de alto potencial que llevan más de 18 meses en su rol sin movimiento. El estancamiento puede aumentar el riesgo de rotación.',
    affectedEmployees: 3,
    affectedTeams: ['team-001', 'team-002'],
    recommendation: 'Programar conversaciones de plan de carrera con Carlos García, Sofía Ramírez y Miguel Torres. Explorar oportunidades de liderazgo técnico o ascenso.',
    confidence: 82,
    createdAt: '2026-04-29T10:00:00Z',
    isRead: true,
  },
  {
    id: 'insight-008',
    type: 'engagement',
    severity: 'critical',
    title: 'Participación en pulsos en mínimo histórico para nuevos ingresos',
    description: 'Los empleados con menos de 6 meses en la empresa tienen una tasa de participación en pulsos del 38%, muy por debajo del 81% general. Esto dificulta detectar problemas de onboarding a tiempo.',
    affectedEmployees: 2,
    affectedTeams: ['team-001', 'team-003'],
    recommendation: 'Revisar la comunicación de la importancia de los pulsos durante el onboarding. Asignar un buddy que refuerce la participación. Considerar pulsos específicos y más cortos para nuevos ingresos.',
    confidence: 94,
    createdAt: '2026-04-28T13:00:00Z',
    isRead: false,
  },
  {
    id: 'insight-009',
    type: 'morale',
    severity: 'info',
    title: 'El reconocimiento entre pares aumentó 35% este mes',
    description: 'El programa de reconocimiento lanzado en Abril está generando impacto positivo. Los reconocimientos entre pares (peer-to-peer) crecieron de 22 a 30 en el último mes, correlacionándose con +4 puntos en engagement.',
    affectedEmployees: 20,
    affectedTeams: ['team-001', 'team-002', 'team-003', 'team-004', 'team-005', 'team-006'],
    recommendation: 'Continuar fomentando el programa de reconocimiento. Publicar un ranking de los reconocedores más activos para generar cultura positiva.',
    confidence: 97,
    createdAt: '2026-04-26T09:30:00Z',
    isRead: true,
  },
  {
    id: 'insight-010',
    type: 'retention',
    severity: 'warning',
    title: 'Departamento de Ventas con mayor índice de rotación previsto',
    description: 'Basado en patrones históricos y señales actuales de desengagement, el modelo de IA proyecta una probabilidad del 34% de que al menos un empleado de Ventas deje la empresa en los próximos 90 días.',
    affectedEmployees: 4,
    affectedTeams: ['team-003'],
    recommendation: 'Revisar la propuesta de valor del equipo de Ventas: compensación variable, herramientas, reconocimiento y trayectoria de carrera. Considerar encuesta de pulso específica para el área.',
    confidence: 79,
    createdAt: '2026-04-24T15:00:00Z',
    isRead: false,
  },
]

// ---------------------------------------------------------------------------
// Recognitions
// ---------------------------------------------------------------------------

export const MOCK_RECOGNITIONS: Recognition[] = [
  {
    id: 'rec-001',
    fromId: 'emp-002',
    fromName: 'María López Hernández',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    toId: 'emp-010',
    toName: 'Sofía Ramírez Duarte',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    message: 'Sofía, los diseños que entregaste para la campaña de Q2 superaron todas las expectativas. Tu creatividad y atención al detalle hacen una diferencia enorme en el equipo. ¡Gracias por tu dedicación!',
    badge: 'Creatividad Excepcional',
    badgeColor: '#f97316',
    badgeIcon: '🎨',
    createdAt: '2026-05-06T16:30:00Z',
    reactions: [
      { emoji: '🎉', count: 5, userReacted: false },
      { emoji: '❤️', count: 3, userReacted: true },
      { emoji: '👏', count: 7, userReacted: false },
    ],
    department: 'Marketing',
    isPublic: true,
  },
  {
    id: 'rec-002',
    fromId: 'emp-006',
    fromName: 'Laura Sánchez Rivera',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    toId: 'emp-001',
    toName: 'Carlos García Morales',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    message: 'Carlos, resolviste un bug crítico en producción en tiempo récord un viernes por la tarde. Tu actitud proactiva y expertise técnico son fundamentales para el equipo. ¡Eres un pilar!',
    badge: 'Héroe del Código',
    badgeColor: '#0c365c',
    badgeIcon: '💻',
    createdAt: '2026-05-05T18:00:00Z',
    reactions: [
      { emoji: '🚀', count: 8, userReacted: true },
      { emoji: '💪', count: 4, userReacted: false },
    ],
    department: 'Ingeniería',
    isPublic: true,
  },
  {
    id: 'rec-003',
    fromId: 'emp-008',
    fromName: 'Patricia Flores Ríos',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    toId: 'emp-014',
    toName: 'Isabella Cruz Medina',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    message: 'Isabella, cerraste 3 procesos de reclutamiento clave esta semana con candidatos de altísima calidad. Tu dedicación para encontrar el mejor talento habla de tu profesionalismo. ¡Excelente trabajo!',
    badge: 'Cazadora de Talentos',
    badgeColor: '#f59e0b',
    badgeIcon: '🏅',
    createdAt: '2026-05-05T12:15:00Z',
    reactions: [
      { emoji: '⭐', count: 6, userReacted: false },
      { emoji: '🙌', count: 3, userReacted: false },
    ],
    department: 'Recursos Humanos',
    isPublic: true,
  },
  {
    id: 'rec-004',
    fromId: 'emp-012',
    fromName: 'Valentina Moreno Castillo',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    toId: 'emp-019',
    toName: 'Rodrigo Blanco Aguirre',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rodrigo',
    message: 'Rodrigo, esta semana atendiste 47 tickets y mantuviste un CSAT de 98%. La cliente Grupo Alfa específicamente te mencionó por nombre en su encuesta de satisfacción. ¡Eso es estar al siguiente nivel!',
    badge: 'Experiencia del Cliente',
    badgeColor: '#10b981',
    badgeIcon: '💎',
    createdAt: '2026-05-04T11:00:00Z',
    reactions: [
      { emoji: '🏆', count: 10, userReacted: true },
      { emoji: '❤️', count: 5, userReacted: false },
      { emoji: '👏', count: 8, userReacted: false },
    ],
    department: 'Éxito del Cliente',
    isPublic: true,
  },
  {
    id: 'rec-005',
    fromId: 'emp-009',
    fromName: 'Diego Hernández Mora',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    toId: 'emp-016',
    toName: 'Camila Jiménez Serrano',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Camila',
    message: 'Camila, tu investigación de usuarios para el rediseño del onboarding fue brillante. Tus insights cambiaron completamente nuestra dirección hacia algo mucho mejor. ¡Gracias por tu rigor y pasión!',
    badge: 'Voz del Usuario',
    badgeColor: '#14b8a6',
    badgeIcon: '🎯',
    createdAt: '2026-05-03T15:30:00Z',
    reactions: [
      { emoji: '🎉', count: 4, userReacted: false },
      { emoji: '🔥', count: 6, userReacted: false },
    ],
    department: 'Producto',
    isPublic: true,
  },
  {
    id: 'rec-006',
    fromId: 'emp-004',
    fromName: 'Ana González Pérez',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    toId: 'emp-003',
    toName: 'Juan Martínez Torres',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan',
    message: 'Juan, a pesar de un mes difícil, cerraste el trimestre con 108% de tu cuota. Tu persistencia y actitud positiva son un ejemplo para todo el equipo. ¡Sigue adelante, esto es solo el comienzo!',
    badge: 'Resiliencia',
    badgeColor: '#8b5cf6',
    badgeIcon: '💪',
    createdAt: '2026-05-02T10:00:00Z',
    reactions: [
      { emoji: '💪', count: 9, userReacted: false },
      { emoji: '🚀', count: 3, userReacted: false },
    ],
    department: 'Ventas',
    isPublic: true,
  },
  {
    id: 'rec-007',
    fromId: 'emp-001',
    fromName: 'Carlos García Morales',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    toId: 'emp-011',
    toName: 'Miguel Ángel Torres Blanco',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Miguel',
    message: 'Miguel, la migración al nuevo servidor fue impecable. Cero downtime, cero problemas para el usuario final. Tu planificación y ejecución fueron de primer nivel. ¡Excelente trabajo en silencio!',
    badge: 'Arquitecto Confiable',
    badgeColor: '#eab308',
    badgeIcon: '⚡',
    createdAt: '2026-05-01T09:45:00Z',
    reactions: [
      { emoji: '🛡️', count: 5, userReacted: true },
      { emoji: '👏', count: 4, userReacted: false },
    ],
    department: 'Ingeniería',
    isPublic: true,
  },
  {
    id: 'rec-008',
    fromId: 'emp-007',
    fromName: 'Roberto Jiménez Castro',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    toId: 'emp-008',
    toName: 'Patricia Flores Ríos',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    message: 'Patricia, el programa de bienestar que implementaste este trimestre ya está mostrando resultados tangibles. El engagement general subió 6 puntos. Gracias por creer y ejecutar con tanta energía.',
    badge: 'Arquitecta de Cultura',
    badgeColor: '#ec4899',
    badgeIcon: '🌟',
    createdAt: '2026-04-30T17:00:00Z',
    reactions: [
      { emoji: '❤️', count: 12, userReacted: false },
      { emoji: '🌟', count: 8, userReacted: true },
    ],
    department: 'Recursos Humanos',
    isPublic: true,
  },
  {
    id: 'rec-009',
    fromId: 'emp-010',
    fromName: 'Sofía Ramírez Duarte',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    toId: 'emp-018',
    toName: 'Natalia Herrera Peña',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natalia',
    message: 'Natalia, el experimento de growth que propusiste y ejecutaste nos trajo 340 nuevos usuarios en una semana. ¡Mente brillante y ejecución impecable! Es un placer trabajar contigo.',
    badge: 'Crecimiento Imparable',
    badgeColor: '#10b981',
    badgeIcon: '📈',
    createdAt: '2026-04-29T14:20:00Z',
    reactions: [
      { emoji: '🚀', count: 11, userReacted: false },
      { emoji: '🎉', count: 7, userReacted: false },
    ],
    department: 'Marketing',
    isPublic: true,
  },
  {
    id: 'rec-010',
    fromId: 'emp-015',
    fromName: 'Alejandro Vargas Núñez',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro',
    toId: 'emp-009',
    toName: 'Diego Hernández Mora',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    message: 'Diego, gracias por escuchar todas mis propuestas de análisis y darles espacio en el roadmap. Tu apertura a los datos convierte buenas ideas en gran impacto. ¡Un líder de producto de verdad!',
    badge: 'Liderazgo Basado en Datos',
    badgeColor: '#6366f1',
    badgeIcon: '📊',
    createdAt: '2026-04-28T11:30:00Z',
    reactions: [
      { emoji: '💡', count: 6, userReacted: false },
      { emoji: '👏', count: 4, userReacted: true },
    ],
    department: 'Producto',
    isPublic: true,
  },
  {
    id: 'rec-011',
    fromId: 'emp-019',
    fromName: 'Rodrigo Blanco Aguirre',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rodrigo',
    toId: 'emp-012',
    toName: 'Valentina Moreno Castillo',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    message: 'Vale, siempre encuentras la manera de motivarnos incluso en las semanas más difíciles. Eres la mejor líder que he tenido. Gracias por confiar en nosotros y darnos espacio para crecer.',
    badge: 'Inspiración del Equipo',
    badgeColor: '#f97316',
    badgeIcon: '🌟',
    createdAt: '2026-04-27T09:00:00Z',
    reactions: [
      { emoji: '❤️', count: 9, userReacted: false },
      { emoji: '🫂', count: 5, userReacted: false },
    ],
    department: 'Éxito del Cliente',
    isPublic: true,
  },
  {
    id: 'rec-012',
    fromId: 'emp-020',
    fromName: 'Daniela Ortega Lozano',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniela',
    toId: 'emp-005',
    toName: 'Luis Rodríguez Vega',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luis',
    message: 'Luis, aunque llevas poco tiempo, ya estás aportando mucho al equipo. Tu entusiasmo y disposición para aprender son contagiosos. ¡Bienvenido al equipo, va a ser increíble trabajar contigo!',
    badge: 'Gran Comienzo',
    badgeColor: '#14b8a6',
    badgeIcon: '🌱',
    createdAt: '2026-04-25T16:45:00Z',
    reactions: [
      { emoji: '🎉', count: 8, userReacted: false },
      { emoji: '💚', count: 4, userReacted: false },
    ],
    department: 'Ingeniería',
    isPublic: true,
  },
  {
    id: 'rec-013',
    fromId: 'emp-003',
    fromName: 'Juan Martínez Torres',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan',
    toId: 'emp-013',
    toName: 'Fernando Reyes Gutiérrez',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fernando',
    message: 'Fernando, aprendiste en tiempo récord todo el stack de herramientas de ventas. Tu adaptación y energía esta semana fueron impresionantes. ¡Vas a llegar muy lejos en esta empresa!',
    badge: 'Aprendizaje Acelerado',
    badgeColor: '#8b5cf6',
    badgeIcon: '⚡',
    createdAt: '2026-04-24T13:15:00Z',
    reactions: [
      { emoji: '🚀', count: 3, userReacted: false },
      { emoji: '👍', count: 2, userReacted: true },
    ],
    department: 'Ventas',
    isPublic: false,
  },
  {
    id: 'rec-014',
    fromId: 'emp-016',
    fromName: 'Camila Jiménez Serrano',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Camila',
    toId: 'emp-020',
    toName: 'Daniela Ortega Lozano',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniela',
    message: 'Daniela, los flujos de diseño que propusiste para el nuevo dashboard de métricas son exactamente lo que el usuario necesitaba. Tus prototipos siempre cuentan una historia clara. ¡Eres increíble!',
    badge: 'Claridad Visual',
    badgeColor: '#f97316',
    badgeIcon: '✨',
    createdAt: '2026-04-23T10:00:00Z',
    reactions: [
      { emoji: '🎨', count: 6, userReacted: false },
      { emoji: '❤️', count: 4, userReacted: false },
    ],
    department: 'Producto',
    isPublic: true,
  },
  {
    id: 'rec-015',
    fromId: 'emp-014',
    fromName: 'Isabella Cruz Medina',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    toId: 'emp-007',
    toName: 'Roberto Jiménez Castro',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    message: 'Roberto, gracias por tomarte el tiempo de responder personalmente a mi idea en el canal de innovación. Ese tipo de atención hace que uno quiera dar lo mejor de sí todos los días. ¡Un líder de verdad!',
    badge: 'Liderazgo Cercano',
    badgeColor: '#0c365c',
    badgeIcon: '🤝',
    createdAt: '2026-04-22T14:30:00Z',
    reactions: [
      { emoji: '❤️', count: 14, userReacted: true },
      { emoji: '👏', count: 10, userReacted: false },
    ],
    department: 'Recursos Humanos',
    isPublic: true,
  },
  {
    id: 'rec-016',
    fromId: 'emp-011',
    fromName: 'Miguel Ángel Torres Blanco',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Miguel',
    toId: 'emp-015',
    toName: 'Alejandro Vargas Núñez',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro',
    message: 'Alejandro, el dashboard de métricas de infraestructura que construiste nos ahorra horas de trabajo cada semana. Tus habilidades de análisis y visualización son de otro nivel. ¡Colaboremos más seguido!',
    badge: 'Automatización',
    badgeColor: '#eab308',
    badgeIcon: '🔧',
    createdAt: '2026-04-21T11:00:00Z',
    reactions: [
      { emoji: '🤖', count: 5, userReacted: false },
      { emoji: '👏', count: 3, userReacted: false },
    ],
    department: 'Ingeniería',
    isPublic: false,
  },
  {
    id: 'rec-017',
    fromId: 'emp-018',
    fromName: 'Natalia Herrera Peña',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natalia',
    toId: 'emp-002',
    toName: 'María López Hernández',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    message: 'María, gracias por siempre hacer espacio para nuestras ideas por más locas que sean. El ambiente de creatividad y seguridad psicológica que has creado en el equipo es algo único. ¡Eres una líder increíble!',
    badge: 'Seguridad Psicológica',
    badgeColor: '#167fd0',
    badgeIcon: '🫶',
    createdAt: '2026-04-20T15:00:00Z',
    reactions: [
      { emoji: '❤️', count: 11, userReacted: false },
      { emoji: '🌈', count: 4, userReacted: false },
    ],
    department: 'Marketing',
    isPublic: true,
  },
  {
    id: 'rec-018',
    fromId: 'emp-005',
    fromName: 'Luis Rodríguez Vega',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luis',
    toId: 'emp-001',
    toName: 'Carlos García Morales',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    message: 'Carlos, gracias por tu paciencia al explicarme la arquitectura del sistema en mi primera semana. Tu mentoría informal me ayudó a ser productivo desde el primer día. ¡Qué suerte tengo de ser tu compañero!',
    badge: 'Mentor del Día a Día',
    badgeColor: '#10b981',
    badgeIcon: '🎓',
    createdAt: '2026-04-19T09:30:00Z',
    reactions: [
      { emoji: '🫂', count: 7, userReacted: false },
      { emoji: '💚', count: 5, userReacted: true },
    ],
    department: 'Ingeniería',
    isPublic: false,
  },
  {
    id: 'rec-019',
    fromId: 'emp-009',
    fromName: 'Diego Hernández Mora',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    toId: 'emp-006',
    toName: 'Laura Sánchez Rivera',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    message: 'Laura, tu manera de manejar la crisis del lanzamiento la semana pasada fue admirable. Mantuviste la calma, tomaste decisiones rápidas y protegiste al equipo. Así es como se lidera bajo presión.',
    badge: 'Liderazgo Bajo Presión',
    badgeColor: '#0c365c',
    badgeIcon: '🧠',
    createdAt: '2026-04-18T17:00:00Z',
    reactions: [
      { emoji: '💙', count: 9, userReacted: false },
      { emoji: '👑', count: 6, userReacted: false },
    ],
    department: 'Ingeniería',
    isPublic: true,
  },
  {
    id: 'rec-020',
    fromId: 'emp-007',
    fromName: 'Roberto Jiménez Castro',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    toId: 'emp-012',
    toName: 'Valentina Moreno Castillo',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    message: 'Valentina, la renovación de Grupo Empresarial Noreste que cerraste esta semana es el contrato más grande en la historia de Customer Success. Tu relación con el cliente y tu propuesta de valor fueron perfectas.',
    badge: 'Logro Histórico',
    badgeColor: '#f59e0b',
    badgeIcon: '🏆',
    createdAt: '2026-04-17T12:00:00Z',
    reactions: [
      { emoji: '🥂', count: 15, userReacted: true },
      { emoji: '🎉', count: 12, userReacted: false },
      { emoji: '🏆', count: 8, userReacted: false },
    ],
    department: 'Éxito del Cliente',
    isPublic: true,
  },
  {
    id: 'rec-021',
    fromId: 'emp-004',
    fromName: 'Ana González Pérez',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    toId: 'emp-018',
    toName: 'Natalia Herrera Peña',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natalia',
    message: 'Natalia, el caso de estudio que escribiste sobre nuestra estrategia de adquisición fue usado en una presentación para inversores. Tu claridad para comunicar logros complejos es un superpoder.',
    badge: 'Comunicación de Impacto',
    badgeColor: '#6366f1',
    badgeIcon: '✍️',
    createdAt: '2026-04-16T10:30:00Z',
    reactions: [
      { emoji: '📝', count: 5, userReacted: false },
      { emoji: '💡', count: 7, userReacted: false },
    ],
    department: 'Marketing',
    isPublic: true,
  },
  {
    id: 'rec-022',
    fromId: 'emp-006',
    fromName: 'Laura Sánchez Rivera',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    toId: 'emp-015',
    toName: 'Alejandro Vargas Núñez',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro',
    message: 'Alejandro, tu modelo predictivo de churn fue presentado a la junta y recibió elogios de todos. Es exactamente el tipo de trabajo que diferencia a CLIMA AI de la competencia. ¡Estoy muy orgullosa de tenerte!',
    badge: 'Innovación en Datos',
    badgeColor: '#0c365c',
    badgeIcon: '🔬',
    createdAt: '2026-04-15T16:00:00Z',
    reactions: [
      { emoji: '🔬', count: 8, userReacted: false },
      { emoji: '🚀', count: 6, userReacted: true },
    ],
    department: 'Ingeniería',
    isPublic: true,
  },
  {
    id: 'rec-023',
    fromId: 'emp-019',
    fromName: 'Rodrigo Blanco Aguirre',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rodrigo',
    toId: 'emp-014',
    toName: 'Isabella Cruz Medina',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    message: 'Isabella, el nuevo proceso de entrevistas que diseñaste hace que los candidatos salgan felices incluso cuando no son seleccionados. Eso dice todo sobre tu talento para las relaciones humanas.',
    badge: 'Experiencia Candidato',
    badgeColor: '#ec4899',
    badgeIcon: '💝',
    createdAt: '2026-04-14T13:45:00Z',
    reactions: [
      { emoji: '💝', count: 7, userReacted: false },
      { emoji: '👏', count: 5, userReacted: false },
    ],
    department: 'Recursos Humanos',
    isPublic: true,
  },
  {
    id: 'rec-024',
    fromId: 'emp-013',
    fromName: 'Fernando Reyes Gutiérrez',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fernando',
    toId: 'emp-004',
    toName: 'Ana González Pérez',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    message: 'Ana, en mi primera semana de onboarding te tomaste 2 horas para revisar mi pitch conmigo. Ese nivel de atención de una directora fue inesperado y significativo. Gracias por creer en mí desde el día uno.',
    badge: 'Mentora Ejecutiva',
    badgeColor: '#8b5cf6',
    badgeIcon: '💜',
    createdAt: '2026-04-13T09:00:00Z',
    reactions: [
      { emoji: '💜', count: 6, userReacted: false },
      { emoji: '🌟', count: 4, userReacted: false },
    ],
    department: 'Ventas',
    isPublic: false,
  },
  {
    id: 'rec-025',
    fromId: 'emp-001',
    fromName: 'Carlos García Morales',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    toId: 'emp-009',
    toName: 'Diego Hernández Mora',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    message: 'Diego, gracias por mantener las especificaciones técnicas tan claras y actualizadas. Nunca tenemos que adivinar qué tiene que hacer el producto. Eso nos permite trabajar mucho más rápido y con menos errores.',
    badge: 'Claridad Técnica',
    badgeColor: '#14b8a6',
    badgeIcon: '📋',
    createdAt: '2026-04-12T14:00:00Z',
    reactions: [
      { emoji: '📋', count: 5, userReacted: false },
      { emoji: '👍', count: 3, userReacted: true },
    ],
    department: 'Producto',
    isPublic: true,
  },
  {
    id: 'rec-026',
    fromId: 'emp-002',
    fromName: 'María López Hernández',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    toId: 'emp-007',
    toName: 'Roberto Jiménez Castro',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    message: 'Roberto, la carta que enviaste a todo el equipo reconociendo nuestro esfuerzo en Q1 fue lo más bonito que he leído en una empresa. Gracias por recordarnos por qué hacemos lo que hacemos.',
    badge: 'Comunicación Humana',
    badgeColor: '#167fd0',
    badgeIcon: '💌',
    createdAt: '2026-04-11T11:30:00Z',
    reactions: [
      { emoji: '💌', count: 18, userReacted: true },
      { emoji: '❤️', count: 15, userReacted: false },
    ],
    department: 'Dirección General',
    isPublic: true,
  },
  {
    id: 'rec-027',
    fromId: 'emp-008',
    fromName: 'Patricia Flores Ríos',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    toId: 'emp-019',
    toName: 'Rodrigo Blanco Aguirre',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rodrigo',
    message: 'Rodrigo, organizaste el evento de team building del área de CS con cero presupuesto adicional y fue el mejor evento del trimestre. Tu creatividad y energía para el equipo son invaluables.',
    badge: 'Espíritu de Equipo',
    badgeColor: '#f97316',
    badgeIcon: '🎊',
    createdAt: '2026-04-10T16:30:00Z',
    reactions: [
      { emoji: '🎊', count: 9, userReacted: false },
      { emoji: '🥳', count: 7, userReacted: false },
    ],
    department: 'Éxito del Cliente',
    isPublic: true,
  },
  {
    id: 'rec-028',
    fromId: 'emp-015',
    fromName: 'Alejandro Vargas Núñez',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro',
    toId: 'emp-011',
    toName: 'Miguel Ángel Torres Blanco',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Miguel',
    message: 'Miguel, configuraste el ambiente de desarrollo de Machine Learning en un día cuando normalmente toma una semana. Me desbloqueaste completamente. ¡Eres un crack de la infraestructura!',
    badge: 'Desbloqueador de Equipos',
    badgeColor: '#eab308',
    badgeIcon: '🔓',
    createdAt: '2026-04-09T10:00:00Z',
    reactions: [
      { emoji: '🔓', count: 4, userReacted: false },
      { emoji: '🚀', count: 5, userReacted: false },
    ],
    department: 'Ingeniería',
    isPublic: false,
  },
  {
    id: 'rec-029',
    fromId: 'emp-020',
    fromName: 'Daniela Ortega Lozano',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniela',
    toId: 'emp-010',
    toName: 'Sofía Ramírez Duarte',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    message: 'Sofía, los motion graphics que creaste para la presentación del producto son los mejores que he visto en una startup. Elevaste toda la presentación a otro nivel. ¡Aprendes algo de ti cada semana!',
    badge: 'Magia Visual',
    badgeColor: '#f97316',
    badgeIcon: '✨',
    createdAt: '2026-04-08T15:00:00Z',
    reactions: [
      { emoji: '✨', count: 10, userReacted: false },
      { emoji: '🎨', count: 8, userReacted: true },
    ],
    department: 'Marketing',
    isPublic: true,
  },
  {
    id: 'rec-030',
    fromId: 'emp-012',
    fromName: 'Valentina Moreno Castillo',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    toId: 'emp-016',
    toName: 'Camila Jiménez Serrano',
    toAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Camila',
    message: 'Camila, el mapa de journey del cliente que construiste junto con mi equipo nos permitió identificar 3 puntos de fricción que no habíamos visto. Gracias por tender puentes entre Producto y CS.',
    badge: 'Puente entre Equipos',
    badgeColor: '#14b8a6',
    badgeIcon: '🌉',
    createdAt: '2026-04-07T11:00:00Z',
    reactions: [
      { emoji: '🌉', count: 6, userReacted: false },
      { emoji: '🤝', count: 4, userReacted: false },
    ],
    department: 'Producto',
    isPublic: true,
  },
]

// ---------------------------------------------------------------------------
// Announcements
// ---------------------------------------------------------------------------

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-001',
    title: '🎉 ¡Celebramos 7 años de CLIMA AI!',
    content: 'Este mes marcamos 7 años desde que iniciamos este proyecto con un equipo de 3 personas y un sueño: transformar la manera en que las empresas cuidan a su gente. Hoy somos 20 personas apasionadas, con clientes en 8 países y un producto que cambia vidas laborales todos los días. Este logro es de todos. La semana del 12 de mayo tendremos una celebración especial — los detalles llegan muy pronto. Mientras tanto, gracias infinitas por ser parte de esta historia.',
    authorId: 'emp-007',
    authorName: 'Roberto Jiménez Castro',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    createdAt: '2026-05-07T10:00:00Z',
    publishedAt: '2026-05-07T10:00:00Z',
    status: 'published',
    targetAudience: 'all',
    readCount: 18,
    totalEmployees: 20,
    pinned: true,
    category: 'achievement',
  },
  {
    id: 'ann-002',
    title: 'Nueva política de trabajo híbrido 2026',
    content: 'A partir del 1 de junio 2026, implementamos nuestra nueva política de trabajo híbrido. Los puntos principales son: mínimo 2 días presenciales al mes en las oficinas de la ciudad correspondiente; total libertad para elegir qué días; los miércoles quedan designados como "Día de Colaboración" donde todos los que puedan asistir se reúnen. RRHH enviará el documento completo de política esta semana. Cualquier duda, Patricia y su equipo están disponibles. El objetivo es lo mejor de ambos mundos: flexibilidad y conexión humana.',
    authorId: 'emp-008',
    authorName: 'Patricia Flores Ríos',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    createdAt: '2026-05-06T09:00:00Z',
    publishedAt: '2026-05-06T09:00:00Z',
    status: 'published',
    targetAudience: 'all',
    readCount: 16,
    totalEmployees: 20,
    pinned: true,
    category: 'policy',
  },
  {
    id: 'ann-003',
    title: 'Resultados Q1 2026: ¡Trimestre histórico!',
    content: 'Cerramos Q1 con los mejores resultados en la historia de la empresa: ARR creció 67% YoY, incorporamos 12 nuevos clientes enterprise, nuestro NPS de clientes alcanzó 72 (el mejor desde que medimos), y el equipo de ventas superó su cuota global en 23%. Estos números son el resultado del trabajo extraordinario de cada uno de ustedes. En el All-Hands del viernes 10 de mayo compartiremos todos los detalles y el rumbo para Q2. ¡Nos vemos ahí!',
    authorId: 'emp-007',
    authorName: 'Roberto Jiménez Castro',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    createdAt: '2026-04-30T16:00:00Z',
    publishedAt: '2026-04-30T16:00:00Z',
    status: 'published',
    targetAudience: 'all',
    readCount: 20,
    totalEmployees: 20,
    pinned: false,
    category: 'achievement',
  },
  {
    id: 'ann-004',
    title: 'Programa de Bienestar Mayo: Semana de la Salud Mental',
    content: 'Durante la semana del 19 al 23 de mayo organizamos la Primera Semana de Salud Mental de CLIMA AI. Las actividades incluyen: taller de manejo del estrés (lunes 10am), sesión de meditación guiada (miércoles 8am), charla con psicóloga organizacional (jueves 4pm) y cierre con ejercicio de gratitud en equipo (viernes 11am). Todas las actividades son opcionales pero altamente recomendadas. Registrarse en el canal #bienestar de Slack. La salud mental no es un lujo, es una prioridad.',
    authorId: 'emp-008',
    authorName: 'Patricia Flores Ríos',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    createdAt: '2026-05-05T11:00:00Z',
    publishedAt: '2026-05-05T11:00:00Z',
    status: 'published',
    targetAudience: 'all',
    readCount: 14,
    totalEmployees: 20,
    pinned: false,
    category: 'event',
  },
  {
    id: 'ann-005',
    title: 'Actualización del proceso de gastos y reembolsos',
    content: 'A partir del 15 de mayo, usaremos Ramp como nuestra plataforma de gastos corporativos. Todos los colaboradores recibirán una tarjeta corporativa virtual en los próximos días. Los gastos aprobados ya no necesitan anticipos ni reembolsos posteriores — simplemente se cargan a la tarjeta. Los límites por categoría están en el documento adjunto en Notion. El proceso de aprobación previa sigue igual para gastos mayores a S/ 1,000. Isabella de RRHH hará una sesión de capacitación el martes 13 de mayo a las 3pm.',
    authorId: 'emp-008',
    authorName: 'Patricia Flores Ríos',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    createdAt: '2026-05-04T14:00:00Z',
    publishedAt: '2026-05-04T14:00:00Z',
    status: 'published',
    targetAudience: 'all',
    readCount: 11,
    totalEmployees: 20,
    pinned: false,
    category: 'update',
  },
  {
    id: 'ann-006',
    title: 'Plan de Carrera 2026: Nuevas trayectorias disponibles',
    content: 'Hemos actualizado nuestras trayectorias de carrera para todos los departamentos. Los puntos más importantes: creamos el rol de "Senior Specialist" como alternativa al camino de management para quienes prefieran profundizar en su área de expertise; actualizamos los criterios de promoción con métricas más claras y objetivas; agregamos la trayectoria de "Technical Lead" en Ingeniería. Cada manager tendrá 1:1 de plan de carrera con su equipo en mayo. Los documentos actualizados están en Notion > Personas > Plan de Carrera.',
    authorId: 'emp-008',
    authorName: 'Patricia Flores Ríos',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    createdAt: '2026-05-02T10:00:00Z',
    publishedAt: '2026-05-02T10:00:00Z',
    status: 'published',
    targetAudience: 'all',
    readCount: 19,
    totalEmployees: 20,
    pinned: false,
    category: 'general',
  },
]

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    type: 'pulse',
    title: 'Nuevo pulso disponible',
    message: 'El pulso "Medición eNPS Mayo 2026" está esperando tu respuesta. Solo toma 2 minutos.',
    createdAt: '2026-05-05T10:00:00Z',
    isRead: false,
    actionUrl: '/empleado/pulso',
    icon: '📊',
    fromName: 'CLIMA AI',
  },
  {
    id: 'notif-002',
    type: 'recognition',
    title: 'Te han reconocido',
    message: 'Carlos García te envió un reconocimiento por tu excelente trabajo esta semana.',
    createdAt: '2026-05-05T18:00:00Z',
    isRead: false,
    actionUrl: '/empleado/reconocimientos',
    icon: '🏆',
    fromName: 'Carlos García Morales',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
  },
  {
    id: 'notif-003',
    type: 'announcement',
    title: 'Nuevo anuncio de Roberto',
    message: 'Roberto Jiménez publicó: "¡Celebramos 7 años de CLIMA AI!"',
    createdAt: '2026-05-07T10:05:00Z',
    isRead: false,
    actionUrl: '/empleado/anuncios',
    icon: '📢',
    fromName: 'Roberto Jiménez Castro',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
  },
  {
    id: 'notif-004',
    type: 'achievement',
    title: '¡Racha de 14 días!',
    message: 'Llevas 14 días respondiendo pulsos consecutivamente. ¡Sigue así, eres un ejemplo!',
    createdAt: '2026-05-06T09:00:00Z',
    isRead: true,
    actionUrl: '/empleado/perfil',
    icon: '🔥',
  },
  {
    id: 'notif-005',
    type: 'alert',
    title: 'Recordatorio: pulso semanal',
    message: 'No olvides responder el pulso de bienestar de esta semana antes del viernes.',
    createdAt: '2026-05-06T08:00:00Z',
    isRead: true,
    actionUrl: '/empleado/pulso',
    icon: '⏰',
  },
  {
    id: 'notif-006',
    type: 'recognition',
    title: '¡Reacción en tu reconocimiento!',
    message: 'Diego Hernández y 4 personas más reaccionaron al reconocimiento que enviaste a Camila.',
    createdAt: '2026-05-03T16:00:00Z',
    isRead: true,
    actionUrl: '/empleado/reconocimientos',
    icon: '❤️',
    fromName: 'Diego Hernández Mora',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
  },
  {
    id: 'notif-007',
    type: 'announcement',
    title: 'Nueva política de trabajo híbrido',
    message: 'Patricia Flores publicó la nueva política de trabajo híbrido para 2026. ¡Léela!',
    createdAt: '2026-05-06T09:05:00Z',
    isRead: false,
    actionUrl: '/empleado/anuncios',
    icon: '📋',
    fromName: 'Patricia Flores Ríos',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
  },
  {
    id: 'notif-008',
    type: 'achievement',
    title: '¡Nueva insignia desbloqueada!',
    message: 'Ganaste la insignia "Colaborador" por apoyar constantemente a tus compañeros de equipo.',
    createdAt: '2026-04-01T12:00:00Z',
    isRead: true,
    actionUrl: '/empleado/perfil',
    icon: '🤝',
  },
  {
    id: 'notif-009',
    type: 'pulse',
    title: 'Resultados del pulso disponibles',
    message: 'Los resultados de la "Encuesta de Compromiso Q2 2026" ya están disponibles.',
    createdAt: '2026-04-16T10:00:00Z',
    isRead: true,
    actionUrl: '/admin/pulsos',
    icon: '📈',
  },
  {
    id: 'notif-010',
    type: 'recognition',
    title: 'Te han reconocido',
    message: 'Valentina Moreno te envió un reconocimiento. ¡Abre para leer el mensaje!',
    createdAt: '2026-04-27T09:05:00Z',
    isRead: true,
    actionUrl: '/empleado/reconocimientos',
    icon: '🌟',
    fromName: 'Valentina Moreno Castillo',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
  },
  {
    id: 'notif-011',
    type: 'alert',
    title: 'Insight de IA disponible',
    message: 'Se detectó un patrón de riesgo en el equipo de Ventas. Revisa el insight para más detalles.',
    createdAt: '2026-05-06T10:05:00Z',
    isRead: false,
    actionUrl: '/admin/insights',
    icon: '🤖',
  },
  {
    id: 'notif-012',
    type: 'announcement',
    title: 'Resultados Q1 disponibles',
    message: 'Roberto publicó los resultados del primer trimestre. ¡Fue un trimestre histórico!',
    createdAt: '2026-04-30T16:05:00Z',
    isRead: true,
    actionUrl: '/empleado/anuncios',
    icon: '🎯',
    fromName: 'Roberto Jiménez Castro',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
  },
  {
    id: 'notif-013',
    type: 'achievement',
    title: 'Tu equipo alcanzó una meta',
    message: 'El equipo de Marketing logró 90%+ de engagement por tercer mes consecutivo. ¡Orgullo de equipo!',
    createdAt: '2026-05-01T11:00:00Z',
    isRead: true,
    actionUrl: '/empleado/mi-equipo',
    icon: '🏅',
  },
  {
    id: 'notif-014',
    type: 'pulse',
    title: 'Pulso de bienvenida',
    message: 'Como parte de tu proceso de onboarding, tenemos un pulso breve esperando tu respuesta.',
    createdAt: '2026-05-01T09:00:00Z',
    isRead: true,
    actionUrl: '/empleado/pulso',
    icon: '👋',
  },
  {
    id: 'notif-015',
    type: 'recognition',
    title: 'Mención en el feed de reconocimientos',
    message: 'Sofía Ramírez mencionó tu nombre positivamente en el feed público de reconocimientos.',
    createdAt: '2026-04-08T15:05:00Z',
    isRead: true,
    actionUrl: '/empleado/reconocimientos',
    icon: '💬',
    fromName: 'Sofía Ramírez Duarte',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
  },
]

// ---------------------------------------------------------------------------
// KPI Metrics
// ---------------------------------------------------------------------------

export const MOCK_KPI_METRICS: KpiMetric[] = [
  {
    id: 'kpi-001',
    label: 'Engagement General',
    value: 74,
    previousValue: 68,
    unit: '%',
    trend: 'up',
    trendValue: 6,
    color: '#167fd0',
  },
  {
    id: 'kpi-002',
    label: 'eNPS',
    value: 42,
    previousValue: 38,
    unit: '',
    trend: 'up',
    trendValue: 4,
    color: '#10b981',
  },
  {
    id: 'kpi-003',
    label: 'Tasa de Rotación',
    value: 8.3,
    previousValue: 11.2,
    unit: '%',
    trend: 'down',
    trendValue: 2.9,
    color: '#f59e0b',
  },
  {
    id: 'kpi-004',
    label: 'Participación en Pulsos',
    value: 81,
    previousValue: 74,
    unit: '%',
    trend: 'up',
    trendValue: 7,
    color: '#8b5cf6',
  },
  {
    id: 'kpi-005',
    label: 'Empleados en Riesgo',
    value: 4,
    previousValue: 6,
    unit: '',
    trend: 'down',
    trendValue: 2,
    color: '#ef4444',
  },
  {
    id: 'kpi-006',
    label: 'Reconocimientos (30d)',
    value: 30,
    previousValue: 22,
    unit: '',
    trend: 'up',
    trendValue: 8,
    color: '#f97316',
  },
]

// ---------------------------------------------------------------------------
// Monthly Engagement Data (last 12 months)
// ---------------------------------------------------------------------------

export const MOCK_ENGAGEMENT_DATA: EngagementDataPoint[] = [
  { date: 'May 2025', score: 62, participation: 65, enps: 28 },
  { date: 'Jun 2025', score: 64, participation: 68, enps: 30 },
  { date: 'Jul 2025', score: 63, participation: 66, enps: 29 },
  { date: 'Ago 2025', score: 65, participation: 70, enps: 32 },
  { date: 'Sep 2025', score: 67, participation: 72, enps: 33 },
  { date: 'Oct 2025', score: 66, participation: 69, enps: 31 },
  { date: 'Nov 2025', score: 68, participation: 73, enps: 34 },
  { date: 'Dic 2025', score: 65, participation: 67, enps: 30 },
  { date: 'Ene 2026', score: 67, participation: 71, enps: 35 },
  { date: 'Feb 2026', score: 70, participation: 76, enps: 38 },
  { date: 'Mar 2026', score: 72, participation: 78, enps: 40 },
  { date: 'Abr 2026', score: 74, participation: 81, enps: 42 },
]

// ---------------------------------------------------------------------------
// Department Engagement
// ---------------------------------------------------------------------------

export const MOCK_DEPARTMENT_ENGAGEMENT: DepartmentEngagement[] = [
  { department: 'Marketing', score: 88, employees: 3, risk: 14 },
  { department: 'RRHH', score: 83, employees: 2, risk: 18 },
  { department: 'Éxito del Cliente', score: 79, employees: 3, risk: 25 },
  { department: 'Producto', score: 77, employees: 3, risk: 27 },
  { department: 'Ingeniería', score: 76, employees: 5, risk: 28 },
  { department: 'Ventas', score: 62, employees: 4, risk: 55 },
]

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-001',
    fromId: 'emp-006',
    fromName: 'Laura Sánchez Rivera',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Laura',
    content: 'Hola Carlos, ¿tienes un momento para revisar el PR de autenticación esta tarde? Quiero asegurarme de que esté listo para el release del viernes.',
    createdAt: '2026-05-07T14:30:00Z',
    isRead: false,
    type: 'direct',
  },
  {
    id: 'msg-002',
    fromId: 'emp-008',
    fromName: 'Patricia Flores Ríos',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    content: 'Recordatorio: la sesión de feedback 360 es el próximo miércoles a las 2pm. Por favor confirma tu asistencia respondiendo este mensaje.',
    createdAt: '2026-05-07T11:00:00Z',
    isRead: false,
    type: 'direct',
  },
  {
    id: 'msg-003',
    fromId: 'emp-009',
    fromName: 'Diego Hernández Mora',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diego',
    content: '¿Puedes revisar el doc de especificaciones del nuevo feature de insights? Quiero tu feedback técnico antes de la reunión de refinamiento del jueves.',
    createdAt: '2026-05-06T17:15:00Z',
    isRead: true,
    type: 'direct',
  },
  {
    id: 'msg-004',
    fromId: 'system',
    fromName: 'CLIMA AI',
    fromAvatar: '',
    content: 'Tu pulso semanal está listo. Recuerda que tus respuestas son anónimas y ayudan a mejorar el ambiente de trabajo para todos.',
    createdAt: '2026-05-07T09:00:00Z',
    isRead: true,
    type: 'system',
  },
  {
    id: 'msg-005',
    fromId: 'emp-007',
    fromName: 'Roberto Jiménez Castro',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    content: 'Gran trabajo en la demo de ayer con el cliente de Guadalajara. Tu presentación fue muy clara y profesional. Estamos muy orgullosos del equipo.',
    createdAt: '2026-05-06T12:00:00Z',
    isRead: true,
    type: 'direct',
  },
  {
    id: 'msg-006',
    fromId: 'system',
    fromName: 'CLIMA AI',
    fromAvatar: '',
    content: 'Alerta de bienestar: hemos detectado que tu equipo tiene indicadores de estrés elevados. Considera revisar los insights de IA para más detalles.',
    createdAt: '2026-05-06T10:00:00Z',
    isRead: false,
    type: 'alert',
  },
  {
    id: 'msg-007',
    fromId: 'emp-002',
    fromName: 'María López Hernández',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    content: 'Hola! Necesito el banner del evento de aniversario para el viernes. ¿Puedes confirmarlo? Las especificaciones son 1920x1080px, formato PNG.',
    createdAt: '2026-05-05T16:45:00Z',
    isRead: true,
    type: 'direct',
  },
  {
    id: 'msg-008',
    fromId: 'emp-004',
    fromName: 'Ana González Pérez',
    fromAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    content: 'El cliente Tecnologías del Norte preguntó por la integración con su ERP. ¿Puedes darme un estimado de tiempo de implementación para compartirle?',
    createdAt: '2026-05-05T10:30:00Z',
    isRead: true,
    type: 'direct',
  },
]
